services:
  database:
    image: postgres:16.0-alpine3.18
    env_file:
      - ../.env
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - database
    env_file:
      - ../.env
    ports:
      - "16543:80"

networks:
  default:
    name: "local-network"
    external: true
